[workspace]
members = [
  "bencode",
  "bittorrent-cli",
  "bittorrent-common",
  "bittorrent-core",
  "bittorrent-daemon",
  "bittorrent-remote",
  "magnet-uri",
  "mainline-dht",
  "peer-protocol",
  "tracker-client",
  "tests",
]

resolver = "2" # Recommended for new workspaces

[workspace.dependencies]
sha1 = "0.10"
thiserror = "2.0"
tokio = { version = "1", features = ["full", "tracing"] }
tracing = "0.1"
tracing-subscriber = "0.3"
console-subscriber = "0.5.0"
rand = "0.9.1"

# Test dependencies
tokio-test = "0.4"
tempfile = "3"
wiremock = "0.6"
mockall = "0.12"
serial_test = "3"
