[workspace]
members = [
  "bencode",
  "bittorrent-cli",
  "bittorrent-common",
  "bittorrent-core",
  "magnet-uri",
  "mainline-dht",
  "peer-protocol",
  "tracker-client",
]
resolver = "2" # Recommended for new workspaces

[workspace.dependencies]
sha1 = "0.10"
thiserror = "2.0"
tokio = { version = "1", features = ["full", "tracing"] }
tracing = "0.1"
tracing-subscriber = "0.3"
console-subscriber = "0.5.0"
rand = "0.9.1"
